import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="title" content="Create Next App" />
        <meta
          name="description"
          content="Generated by create next app with Tailwind Css, The best App ever You can try, YOYO!!"
        />

        <meta property="og:type" content="website" />
        <meta
          property="og:url"
          content="https://37983d47009e797059468c94e39dcdf0.loophole.site/"
        />
        <meta property="og:title" content="Create Next App" />
        <meta
          property="og:description"
          content="Generated by create next app with Tailwind Css, The best App ever You can try, YOYO!!"
        />
        <meta property="og:image" content="" />

        <meta property="twitter:card" content="summary_large_image" />
        <meta
          property="twitter:url"
          content="https://37983d47009e797059468c94e39dcdf0.loophole.site/"
        />
        <meta property="twitter:title" content="Create Next App" />
        <meta
          property="twitter:description"
          content="Generated by create next app with Tailwind Css, The best App ever You can try, YOYO!!"
        />
        <meta property="twitter:image" content="" />
      </Head>
      <h1 className="text-4xl font-bold text-indigo-500">Hello world!</h1>
    </>
  );
};

export default Home;
